version: '3.8'

services:
  websocket-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: quantum-chat-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
